const personalInfo = {
  portfolioTitle: "Raciel Antela Pardo",
  portfolioDescription:
    "I'm a software developer with a passion for building full-stack web apps. Check out what I've been working on and get in touch!",
  blogTitle: "Raciel - Blog",
  blogDescription: "I write about web development, tech, and other things.", // Change later, this was generated by Copilot
};

export default personalInfo;
